name: "Main Branch CI"

on:
    pull_request:
        branches:
            - main

jobs:
    test-code-quality:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Testing...🧪"
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
            - run: npm i --location=global yarn
            - run: yarn
            - run: yarn lint
            - name: Test the project
              run: yarn test
            - run: yarn build
            - name: Update Database
              run: yarn db-push
              env:
                DATABASE_URL: ${{ secrets.DATABASE_URL }}
            - run: echo "Test Completed...🤯"
